version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - mode: host
        target: 80
        published: 80
        protocol: tcp
    networks:
      - learnrun_network
    volumes:
      - /home/wg7363/nginx.conf:/etc/nginx/nginx.conf
      - LearnRun_static:/data/static/
      - LearnRun_media:/data/media/
      - LearnRun_log:/var/log/nginx/

  django:
    image: project:5
    networks:
      - learnrun_network
    volumes:
      - LearnRun_static:/home/LearnRun-django-web/staticfiles/
      - LearnRun_media:/home/LearnRun-django-web/media/
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD

  mariadb:
    image: mariadb:10.5
    networks:
      - learnrun_network
    volumes:
      - LearnRun_mariadb:/var/lib/mysql
    secrets:
        - MARIADB_ROOT_PASSWORD
        - MARIADB_USER
        - MARIADB_PASSWORD

    environment:
      MARIADB_DATABASE: django
      MARIADB_USER_FILE: /run/secrets/MARIADB_USER
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD


networks:
  learnrun_network:

volumes:
  LearnRun_static:
  LearnRun_media:
  LearnRun_mariadb:
  LearnRun_log:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true